package hu.progmasters.exceptions2;

public class Exceptions2 {

    public static void main(String[] args) {
        // TODO get an integer with Scanner from console, if it is divisible by 2, calculate the half of it, and print
        // it to the console.
        //
        // Create a custom OddNumberException that extends RuntimeException, and if the number is odd, throw that from
        // inside the calculateHalf() method. Than catch the exception inside the main() method, and print an error
        // message to the console.
        // Optional: get integers from the console again and again, until you get an even one.
        //
        // Why using exceptions is the good solution here in your opinion? Why could you not return the information from
        // calculateHalf() that the input was not valid any other easy way?

    }

    private static int calculateHalf(int number) {
        return 0;
    }
}
